# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

from header_music import *
####################################################################################################################
#  Each track record contains the following fields:
#  1) Track id: used for referencing tracks.
#  2) Track file: filename of the track
#  3) Track flags. See header_music.py for a list of available flags
#  4) Continue Track flags: Shows in which situations or cultures the track can continue playing. See header_music.py for a list of available flags
####################################################################################################################

# WARNING: You MUST add mtf_module_track flag to the flags of the tracks located under module directory

tracks = [
  ("cant_find_this", "cant_find_this.ogg", 0, 0),
  ("Warh_40k", "Warh_40k.ogg", mtf_start_immediately|mtf_sit_main_title, 0),
  ("arena_1", "arena_1.ogg", mtf_sit_arena, 0),
  ("capture", "capture.ogg", mtf_persist_until_finished, 0),
  ("defeated_by_neutral", "defeated_by_neutral.ogg", mtf_persist_until_finished|mtf_sit_killed, 0),
  ("defeated_by_neutral_2", "defeated_by_neutral_2.ogg", mtf_persist_until_finished|mtf_sit_killed, 0),
  ("defeated_by_neutral_3", "defeated_by_neutral_3.ogg", mtf_persist_until_finished|mtf_sit_killed, 0),
  ("empty_village", "empty_village.ogg", mtf_persist_until_finished, 0),
  ("encounter_hostile_nords", "encounter_hostile_nords.ogg", mtf_persist_until_finished|mtf_sit_encounter_hostile, 0),
  ("escape", "escape.ogg", mtf_persist_until_finished, 0),
  ("infiltration_khergit", "infiltration_khergit.ogg", mtf_culture_3|mtf_sit_town_infiltrate, mtf_culture_1|mtf_culture_2|mtf_culture_4|mtf_culture_5|mtf_culture_6),
  ("killed_by_khergit", "killed_by_khergit.ogg", mtf_culture_3|mtf_persist_until_finished|mtf_sit_killed, 0),
  ("killed_by_swadian", "killed_by_swadian.ogg", mtf_culture_1|mtf_persist_until_finished|mtf_sit_killed, 0),
  ("retreat", "retreat.ogg", mtf_persist_until_finished|mtf_sit_killed, 0),
  ("tavern_1", "tavern_1.ogg", mtf_sit_tavern|mtf_sit_feast, 0),
  ("tavern_2", "tavern_2.ogg", mtf_sit_tavern|mtf_sit_feast, 0),
  ("victorious_evil", "victorious_evil.ogg", mtf_persist_until_finished, 0),
  ("victorious_neutral_1", "victorious_neutral_1.ogg", mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("victorious_neutral_2", "victorious_neutral_2.ogg", mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("victorious_neutral_3", "victorious_neutral_3.ogg", mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("victorious_swadian", "victorious_swadian.ogg", mtf_culture_2|mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("victorious_vaegir", "victorious_vaegir.ogg", mtf_culture_2|mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("victorious_vaegir_2", "victorious_vaegir_2.ogg", mtf_culture_2|mtf_persist_until_finished|mtf_sit_victorious, 0),
  ("wedding", "wedding.ogg", mtf_persist_until_finished, 0),
  ("coronation", "coronation.ogg", mtf_persist_until_finished, 0),
  ("no_mer", "no_mer.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("forg_in", "forg_in.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("blac_spi", "blac_spi.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("comi_of", "comi_of.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("jvd_mar_nos", "jvd_mar_nos.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("to_batt_bro", "to_batt_bro.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("jvd_thi_is", "jvd_thi_is.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("the_gre", "the_gre.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("sku_cros", "sku_cros.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("necr_the", "necr_the.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("forg_of", "forg_of.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("leav_non", "leav_non.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("prim_hon", "prim_hon.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("marc_Of", "marc_Of.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("khai_wra", "khai_wra.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("They_Com", "They_Com.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("the_emp_v", "the_emp_v.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("jvd_crus", "jvd_crus.ogg", mtf_sit_fight|mtf_sit_ambushed|mtf_module_track, 0),
  ("The_sie", "The_sie.ogg", mtf_sit_siege|mtf_module_track, mtf_sit_fight|mtf_sit_ambushed),
  ("dark_win", "dark_win.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("pat_the_old", "pat_the_old.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("chan", "chan.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("wid_har", "wid_har.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("ange_sor", "ange_sor.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("win_gab", "win_gab.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("for_the_e", "for_the_e.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("shal_wat", "shal_wat.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("from_th", "from_th.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("grim_pre", "grim_pre.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("defe_rea", "defe_rea.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("mis_loc", "mis_loc.mp3", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("le_serp", "le_serp.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("my_cold", "my_cold.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("shad_for", "shad_for.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("the_len_me", "the_len_me.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("men_Of", "men_Of.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("atta_Of_the", "atta_Of_the.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
  ("dark_asia", "dark_asia.ogg", mtf_sit_travel|mtf_module_track, mtf_sit_tavern|mtf_sit_town|mtf_sit_night),
]